### ISSUE TITLE
Add repeat option to timestamp task

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-task-modules#31]
Having an option to repeat within a task allows to control how long task is running, thus giving better ways to try to test status and cancel operations.

**Comment by markfisher** [comment]
maybe it would be better to add a `repeat` property instead of a sleep, then have the task append the timestamp to the file every second (which would actually make it just a *finite* version of the `time` source app, which is nice)... default for `repeat` is 1, but if you want to run for one minute, pass `repeat=60`

**Comment by jvalkeal** [comment]
@markfisher yes, I think what you proposed is better idea indeed.
